function PoliticaDePrivacidadGrid() {
  return (
    <div className="PoliticaDePrivacidadGrid">
        <h1>Política de privacidad</h1>
    
      <p>Ponemos a su disposición la presente Política de Privacidad con la finalidad de informarle detalladamente sobre cómo tratamos sus datos personales y protegemos su privacidad y la información que nos proporciona. </p>
      <p>Si, en el futuro, introdujésemos modificaciones en esta Política de Privacidad, se lo comunicaremos a través de esta página web o por otros medios, de modo que pueda usted conocer las nuevas condiciones de privacidad que se adopten. </p>
      <p>Le informamos a continuación, en forma de preguntas y respuestas, de las condiciones en las que nuestra entidad trata sus datos personales:</p>
            <h4>¿Quién es el responsable del tratamiento de sus datos?</h4>
            <ul>
              <li>Identidad: UNIVERSIDAD ANTONIO DE NEBRIJA (UNIVERSITAS NEBRISSENSIS, S.A.), en adelante, UNIVERSIDAD NEBRIJA.</li>
              <li>Domicilio social: Campus Universitario de Ciencias de la Vida en La Berzosa, 2824, Hoyo de Manzanares (Madrid).</li>
              <li>Teléfono: 91 452 11 00</li>
              <li>E-mail de contacto:  <a href="mailto:lopd@nebrija.es">lopd@nebrija.es</a></li>
            </ul>
        <h4>¿Quién es el Delegado de Protección de Datos (DPD) de la entidad y cómo puede ayudarte?</h4>
        <p>Le informamos de que disponemos de un Delegado de Protección de Datos (DPD), que es una figura legalmente prevista cuyas funciones principales son las de informar y asesorar a la entidad sobre las obligaciones que le afectan en materia de protección de datos personales y supervisar su cumplimiento. Además, el DPD actúa como punto de contacto con la entidad para cualquier cuestión relativa al tratamiento de datos personales, por lo que, si lo desea, puede usted dirigirse a él:  <a href="mailto:dpo@nebrija.es">dpo@nebrija.es</a></p>
       <h4>¿Con qué finalidad tratamos sus datos personales, cuál es la base legitimadora de dicho tratamiento y durante cuánto tiempo se conservarán?</h4>
            <p>Los datos facilitados serán tratados con las siguientes finalidades, dependiendo del motivo por el que hayan sido entregados:</p>
            <ol>
              <li>Canalizar las solicitudes de información, sugerencias y reclamaciones que nos pueda hacer llegar, contactar con el remitente de la información, dar respuesta a las peticiones efectuadas por los/las usuarios/as a través de cualquiera de las formas de contacto que se ponen a disposición del/la usuario/a y hacer un seguimiento posterior. </li>
              <li>Remisión de comunicaciones comerciales, incluso a través de medios electrónicos. A través de dichas comunicaciones se informará a los/las usuarios/as sobre los diferentes servicios y productos ofrecidos por UNIVERSIDAD NEBRIJA, así como los eventos organizados por la misma. En relación con el envío de las referidas comunicaciones, con base en la información facilitada, podemos elaborar perfiles comerciales, para ofrecerle los productos y servicios que mejor se ajusten a sus intereses. <br />  <br />  Para estas finalidades, los datos serán tratados sobre la base jurídica del consentimiento de la persona que los proporciona. Puede retirarse dicho consentimiento en cualquier momento, si bien ello no afectará a la licitud de los tratamientos efectuados con anterioridad. El hecho de facilitar los datos es voluntario aunque, en caso de no hacerlo, no se podrán tratar para las finalidades indicadas. Por tanto, la comunicación de sus datos personales a estos efectos es un requisito necesario para que podamos atender las peticiones formuladas por esta vía, así como para remitir, en su caso, las comunicaciones comerciales de la entidad.   <br />   <br /> Los datos serán conservados durante el tiempo necesario para dar respuesta a su solicitud, petición, consulta y dar ésta por definitivamente cerrada. Posteriormente, serán conservados a modo de histórico de comunicaciones durante un máximo de un año, salvo que el/a usuario/a solicite su supresión, a cualquiera de las direcciones de contacto referenciadas. <br />  <br />  Si el/la usuario/a consiente el envío de comunicaciones comerciales, los datos podrán almacenarse indefinidamente para esta finalidad, hasta que el/la usuario/a se oponga a la remisión de las mismas. <br />  <br />  Las categorías de datos que se tratarán para estas finalidades serán las siguientes: Datos identificativos y de contacto.</li>
              <li>En caso de que usted nos haya remitido su currículum vítae, sus datos serán tratados para gestionar y tramitar su solicitud de empleo, de conformidad con lo indica en la política de privacidad del portal del candidato: https://www.nebrija.es/rrhh/seleccion/portal/lopd.php</li>
              <li>Tramitar las solicitudes de inscripción y admisión realizadas por los usuarios a cualquiera de los servicios académicos o culturales ofrecidos por la Universidad, así como a las actividades aparejadas. En este supuesto, los datos serán tratados sobre la base de la relación jurídica mantenida entre las partes. El tratamiento de los datos personales es necesario para la correcta admisión e inscripción a las diferentes ofertas educativas y culturales de la Universidad, por lo que es obligatorio que se faciliten los datos personales, siendo imposible tramitar su alta en caso contrario. Los datos serán conservados durante el tiempo que duren los servicios académicos o culturales en los que se haya inscrito y, posteriormente, hasta que prescriban las eventuales responsabilidades que se pudieran derivar de los mismos.</li>
                <li>Gestionar los servicios académicos solicitados por los/las estudiantes, así como cualquier otro servicio que se haya indicado durante el proceso de automatrícula o que sea consecuencia de los estudios universitarios que se realicen en esta Institución (desarrollo de prácticas, participación en eventos, actos académicos, etc). El suministro de los datos con este fin es obligado, siendo imposible que el/la estudiante pueda ser matriculado/a y desarrolle los estudios académicos y servicios solicitados en caso contrario. Como parte de la función académica (ej: trabajos universitarios o evaluaciones), se podrá captar la voz e imagen del/la estudiante. <br />
                <br />  La Universidad Nebrija podrá proceder a la grabación de las pruebas de evaluación virtual/online para garantizar la seguridad a la hora de realizar las mismas y como evidencia de la evaluación. Teniendo en cuenta lo anterior, la grabación efectuada tiene como finalidad garantizar la presencialidad del alumnado, la realización de la prueba y evitar que los/las estudiantes cometan determinadas conductas inapropiadas durante la celebración de las mismas. <br />
                <br /> Este tratamiento de datos tiene su base legitimadora en el cumplimiento de una misión realizada en interés público, en virtud de la Ley Orgánica 2/2023, de 22 de marzo, del Sistema Universitario, así como en la ejecución de la relación contractual existente con el/la estudiante como consecuencia de su matriculación en este centro (Condiciones Generales de Contratación), en relación con aquellos servicios solicitados por estos que no estén directamente relacionados con el servicio público de educación superior. Como parte de la función académica (ej: trabajos universitarios o evaluaciones), se podrá captar la imagen del/la estudiante, teniendo este tratamiento de datos la misma base legitimadora del interés público referenciada. <br />
                <br /> Teniendo en cuenta lo indicado en el párrafo anterior, y fundamentándose en las mismas bases legitimadoras, se podrá llevar a cabo un tratamiento de la imagen y la voz del/la estudiante, como consecuencia del uso de herramientas docentes y tecnología digital que la Universidad utiliza en la prestación del servicio contratado, atendiendo a la modalidad de impartición del programa académico y, en concreto, como consecuencia de la metodología Presencialidad Híbrida y/o Remota, consistente en retransmitir la formación presencial al resto de estudiantes matriculados en la asignatura que acceden a las clases de manera virtual/online (adaptación tecnológica del aula para favorecer el aprendizaje no presencial mediante recursos digitales).<br />
                <br />  Para esta finalidad, se procede a la grabación de las clases impartidas en la Universidad y, por ello, de la imagen y, en su caso, voz del/la estudiante que o bien se encuentra presencialmente en el aula, o bien interactúa a través de herramientas digitales (grupos mixtos). <br />
                <br />  La Universidad difundirá (en tiempo real o diferido) la grabación de las clases a través de las herramientas docentes de la Universidad (plataformas de formación), cuyo acceso estará restringido a los/las estudiantes y profesores de la Universidad, así como a los empleados/as de la Universidad encargados del mantenimiento de dicho sistema, estando prohibida su difusión por el/la estudiante. La grabación de las clases, así como a su difusión, responde a las siguientes finalidades:
                  <ul>
                    <li>Ofrecer la posibilidad de su visionado posterior en modelos de teleformación.</li>
                    <li>Garantizar la accesibilidad a los contenidos por parte de estudiantes que, por diferentes motivos, no pueden acudir presencialmente a las clases o han tenido problemas de conexión. </li>
                    <li>Constituir un material de estudio para la preparación de la evaluación</li>
                  </ul>   
                  Las imágenes podrán ser utilizadas como elemento probatorio de eventuales infracciones cometidas por el/la estudiante de conformidad con lo dispuesto en el Régimen Disciplinario previsto en la normativa interna de aplicación. <br />
                  <br />  El suministro de los datos con este fin es obligado, siendo imposible que el/la estudiante pueda ser matriculado/a y desarrolle los estudios académicos en caso contrario. Para más información sobre la formación híbrida, el/la estudiante podrá consultar al personal académico o de servicios cualquier información adicional sobre Global Campus Nebrija y las tecnologías aplicadas a la impartición híbrida y/o virtual de la docencia.<br />
                  <br />  En ningún caso se permite que los/las estudiantes procedan a las grabaciones de las clases, salvo que hayan solicitado el consentimiento de los asistentes.<br />
                  <br />  Los datos serán conservados durante todo el tiempo que sea estudiante de la Universidad y, aún después, hasta que prescriban las eventuales responsabilidades que se pudieran derivar de la relación académica y durante todo el tiempo exigido por la normativa aplicable. Las grabaciones de las clases para la adopción de un sistema de formación online, como el que puede ir aparejado a la metodología de Presencialidad Híbrida/Remota, así como cualquier otra grabación que tenga una finalidad educativa, estarán disponibles como máximo durante el correspondiente curso académico, salvo que las mismas formen parte de las evidencias de evaluación del alumnado, que se conservarán un máximo de cinco años o hasta que exista resolución firme, como consecuencia de los supuestos de petición de revisión o de recurso contra la calificación o que sirvan como evidencia para un expediente disciplinario. No obstante, se podrá conservar una copia debidamente bloqueada de las grabaciones para el cumplimiento de obligaciones legales a las que deba hacer frente la Universidad y hasta que prescriban las mismas. 
                  <li>Tramitar su inscripción en los diferentes clubes Nebrija (incluido el Club Alumni)y gestionar cualquier actividad aparejada a los mismos. En este supuesto sus datos serán tratados por la Fundación Antonio de Nebrija, como responsable del tratamiento. El tratamiento de los datos es necesario para la correcta inscripción y participación en los clubes Nebrija, siendo esta prestación de servicios la base de dicho tratamiento, por lo que es obligatorio que se faciliten los datos personales, siendo imposible la inscripción en los Clubes en caso contrario. 
                  <br />  <br /> Asimismo, salvo que medie oposición del interesado/a, los datos podrán ser utilizados para remitir información, por medios electrónicos, de los servicios, ofertas y eventos desarrollados por la Fundación. La base del tratamiento es el interés legítimo de la entidad de promocionar sus servicios y actividades. Dicho interés legítimo se reconoce por la normativa legal aplicable (Reglamento General de Protección de Datos), que permite expresamente el tratamiento de datos personales sobre esa base legal con fines de mercadotecnia directa. En cualquier caso, el/la estudiante tiene derecho a oponerse a este tratamiento de sus datos, pudiendo hacerlo por cualquiera de los medios previstos en esta cláusula.<br />
                  <br />  Los datos serán conservados mientras sea miembro de los clubes Nebrija y, aún después, hasta que prescriban las eventuales responsabilidades que se pudieran derivar de su relación con el mismo y durante todo el tiempo exigido por la normativa aplicable. No obstante lo anterior, en el caso de que no se haya opuesto al envío de información comercial, sus datos podrán conservarse de manera indefinida con la finalidad de remitirle comunicaciones comerciales. </li>
                    <li>Durante la participación en las distintas actividades y eventos llevados a cabo por la Universidad se podrán captar imágenes de los participantes (realización de fotografías y vídeos). Cuando el tratamiento forme parte de la función educativa (ej: trabajos universitarios, evaluaciones), se podrá captar la imagen del participante sin su consentimiento, ya que la base legitimadora será el desempeño de la función docente y educadora (relación contractual), así como el cumplimiento de una misión realizada en interés público, siendo obligatorio que el/la interesado/a facilite sus datos para esta finalidad, impidiéndose en otro caso el desempeño de dicha función. No obstante, cuando la captación de las imágenes no se corresponda con dicha función educativa, sino que se trate de imágenes de acontecimientos o eventos que se graban habitualmente con fines de difusión y promoción en la revista de la universidad o en su web o redes sociales, procederemos a recabar el consentimiento de los/las interesados/as, siendo ésta la base legitimadora del tratamiento. </li>
                    <br />  <br /> En cualquier caso, la Universidad se reserva el derecho de realizar fotografías y grabaciones de todas las actividades y eventos que organice, de forma individual o en colaboración con terceros, por lo que el/la interesado/a, en caso de que desee que su imagen y su voz sean captadas y utilizadas con la finalidad de difusión y promoción indicada, deberá manifestar su consentimiento. Cuando no haya manifestado su consentimiento, éste deberá abstenerse de participar voluntariamente en las fotografías y grabaciones que la entidad realice durante los mismos. 
                    <br />    <br /> El tratamiento de su imagen con la finalidad de difusión y promoción indicada no es obligatorio, por lo que, si la persona participante no nos autoriza, sus datos no podrán ser tratados para esta finalidad. El consentimiento podrá ser retirado en cualquier momento, si bien ello no afectará a la licitud de los datos tratados con anterioridad. <br />
                    <br />  En el supuesto de que la imagen del participante se capte de manera accesoria, de acuerdo con la Ley Orgánica 1/82, no será considerado una intromisión ilegítima a la intimidad y a la propia imagen, pudiendo captarse sin necesidad de recabar el consentimiento expreso del afectado, siendo el interés público la base del tratamiento.<br /><br /> 
                    <br /> Para esta finalidad, los datos podrán ser conservados por la Universidad de manera indefinida, salvo que el/la usuario/a se oponga dirigiéndose a cualquier dirección de contacto indicada.
                  </li>
                  <li>En el supuesto de que un/a usuario/a se descargue e instale la aplicación AppCrue, aceptando sus términos y condiciones, los datos personales que se recaben a través de la misma serán tratados con la finalidad de gestionar el alta del/la usuario/a y su participación en los servicios que se ofrecen a través de la aplicación. La base del tratamiento de sus datos será el consentimiento. El/la usuario/a podrá desinstalar la aplicación cuando lo considere oportuno, revocando, en consecuencia, su consentimiento, si bien ello no afectará a la licitud de los datos tratados con anterioridad. El tratamiento de sus datos a través de la aplicación no es obligatorio para el desarrollo de la relación académica o profesional mantenida con la Universidad, si bien el/la interesado/a no podrá disfrutar de las ventajas que ofrece dicha aplicación en caso de que no se descargue la misma autorizando el tratamiento de sus datos. Para el correcto funcionamiento de determinadas funcionalidades de la app se solicitan permisos para acceder a ciertos recursos propios del dispositivo. La activación de los permisos se llevará a cabo a través de ventanas emergentes en las que el/la usuario/a podrá consentir el acceso a los recursos del dispositivo.<br />
                  <br />  Puede consultar información adicional sobre el uso y los distintos servicios ofrecidos por esta aplicación en los siguientes enlaces: <br />
                <ul>
                  <li><a href="https://www.crue.org/aviso-legal/">https://www.crue.org/aviso-legal/</a></li>
                  <li><a href="https://www.crue.org/aviso-legal/#politica-privacidad">https://www.crue.org/aviso-legal/#politica-privacidad</a></li>
                </ul>
                Los datos serán conservados mientras el/la usuario/a haga uso de la aplicación y, posteriormente, mientras pueda surgir algún tipo de responsabilidad legal aparejado al mismo.
              </li>
              <li>La gestión de la relación con el cliente y la facturación y cobro de los servicios ofrecidos a través de la tienda on-line de la UNIVERSIDAD NEBRIJA. En concreto, la gestión de los pedidos realizados (procesar sus pedidos online, incluido el envío de correos electrónicos y/o mensajes de texto para informarle sobre el estado del envío, procesar devoluciones de pedido, contactar con el/la cliente/a en caso de que haya algún problema con alguno de sus pedidos o por otros motivos de logística, etc.). El suministro de los datos con este fin por parte de nuestros clientes es obligado, impidiéndose en otro caso la compra del producto. Los datos para la gestión de la relación con los/las clientes/as, la facturación y cobro de los servicios serán conservados con ese fin durante todo el tiempo en que el contrato esté vigente. Una vez finalizada dicha relación, en su caso, los datos podrán ser conservados durante el tiempo exigido por la legislación aplicable y hasta que prescriban las eventuales responsabilidades derivadas del contrato. La base legal para el tratamiento de los datos de los/las clientes/as es la ejecución del contrato de compraventa según las condiciones generales de venta: <a href="https://tiendanebrija.com/pages/condiciones-generales-de-venta">https://tiendanebrija.com/pages/condiciones-generales-de-venta</a></li>
           <li>Realización de informes estadísticos. Estos informes tienen una doble finalidad:
            <ul>
              <li>Cumplimiento de la obligación legal impuesta a las universidades de analizar la calidad del servicio académico ofrecido. Estos informes serán comunicados a los organismos públicos competentes en materia de educación de manera anonimizada. El tratamiento de los datos para este fin es obligatorio, ya que, de lo contrario, no se podrían efectuar dichos informes</li>
            <li>Valoración interna de la calidad de los servicios docentes ofrecidos por la Universidad Nebrija y proponer mejoras. El tratamiento de los datos de los/las estudiantes para este fin no es obligatorio, en cuyo caso, no se podrán tener en cuenta para efectuar dichos informes. </li>
            </ul>
            Los informes podrán ser publicados, si bien de manera anonimizada.<br />  <br />  Los informes estadísticos serán conservados indefinidamente, si bien los mismos contienen información anonimizada. <br />  <br />  El tratamiento de los datos con una finalidad estadística tiene su base legitimadora tanto en el cumplimiento de una obligación legal, para el caso de los informes que deben entregarse a las autoridades públicas de carácter educativo, como en el interés legítimo, en el caso de los informes internos, el cual se considera prevalente debido a que los resultados serán anónimos, sin que afecte a la privacidad de los/las estudiantes y sin que se traten más datos de los estrictamente necesarios para este fin, siendo el tratamiento proporcional en función de la finalidad perseguida. En cualquier caso, los/las estudiantes podrán oponerse al tratamiento de sus datos con fines estadísticos internos en cualquiera de las direcciones de contacto referenciadas.
           </li>
              </ol>
           <h4>¿Se realizan transferencias internacionales de datos?</h4>
        <p>La Universidad utiliza la plataforma de Mailchimp para enviar sus comunicaciones informativas. Los datos de los destinatarios son almacenados en la plataforma de Mailchimp, que es propiedad y está operado por The Rocket Science Group LLC ubicada en Estados Unidos, por lo que se estaría produciendo una transferencia internacional de datos. Esta entidad ofrece garantías adecuadas de protección de datos al aplicar las Cláusulas Contractuales Tipo aprobadas por la Comisión Europea para las transferencias internacionales de datos. Para más información <a href="https://mailchimp.com/help/mailchimp-european-data-transfers/">https://mailchimp.com/help/mailchimp-european-data-transfers/</a><br /><br />Adicionalmente, los servicios de Call Center están contratados con la empresa LEQUAR, ubicada en Colombia. Esta entidad ofrece garantías adecuadas de protección de datos al aplicar las Cláusulas Contractuales Tipo aprobadas por la Comisión Europea para las transferencias internacionales de datos. Estas cláusulas se encuentran a disposición de los interesados, pudiendo solicitar copia de las mismas en cualquier de las direcciones de contacto referenciadas<br /><br />La Universidad utiliza la plataforma de comercio electrónico Shopify para gestionar los pedidos realizados por los usuarios, almacenándose los datos en sus sistemas. Los datos personales del EEE son recibidos y procesados inicialmente por la entidad irlandesa de Shopify, Shopify International Limitado. No obstante, Shopify Inc. utiliza una combinación de centros de datos y proveedores de servicios en la nube para almacenar esta información personal. Cuando se transfieren datos personales a Estados Unidos, Shopify se basará en Normas Corporativas Vinculantes (BCR) para proteger los datos personales que se transfieren entre las entidades corporativas de Shopify en todo el mundo. Puede obtener más información en el siguiente enlace: Shopify GDPR Whitepaper.</p>
        <h4>¿Cómo tratamos sus datos en Redes Sociales?</h4>
        <p>En caso de que se haga amigo/a o seguidor/a nuestro en redes sociales, trataremos sus datos para mantenerle informado de nuestras actividades y promociones a través de dichos canales. Estos datos serán tratados sobre la base jurídica de su consentimiento y serán conservados mientras usted permanezca como amigo/a o seguidor/a nuestro, pudiendo revocar su consentimiento en cualquier momento, si bien ello no afectará a la licitud de los tratamientos efectuados con anterioridad. El hecho de facilitar los datos con este fin es voluntario, aunque, en caso de no hacerlo, no podrá ser amigo/a o seguidor/a en las redes sociales en que tengamos. </p> 
        <p>En aquellos casos en que el registro de usuario/a se efectúa mediante redes sociales, los datos personales que trataremos procederán de la red social de que se trate, a la que, previamente, el interesado habrá facilitado dichos datos para los fines previstos en sus correspondientes políticas de privacidad. Las categorías de datos que recabaremos desde la red social de que se trate son las que figuran en nuestro formulario de registro y que tu hayas facilitado a dicha red social. Si, para proceder al registro en nuestra web, fuesen imprescindibles más datos de los suministrados por la red social, deberás cumplimentarlos adicionalmente en nuestro formulario de registro, con sujeción a las condiciones de privacidad previstas en esta cláusula. </p>
        <h4>¿Cómo tratamos sus datos en las llamadas del Call Center o cualquier Centralita telefónica de los campus universitarios, incluidas las llamadas atendidas por aplicaciones tecnológicas -como Teams-?</h4>
        <p>Le informamos de que las llamadas al Call Center o cualquier Centralita telefónica de los campus universitarios, incluidas las llamadas atendidas por aplicaciones tecnológicas -como Teams- de UNIVERSIDAD NEBRIJA podrán ser grabadas para dar curso a su solicitud o responder su consulta, duda o sugerencia, así como para valorar la calidad de la respuesta dada por nuestros agentes/empleados o, en su caso, para gestionar acciones y propuestas comerciales.</p>
        <p>Sus datos, incluyendo su número de teléfono que quedará registrado en la centralita, serán tratados sobre la base del interés legítimo de la Universidad de disponer de instrumentos para poder justificar el cumplimiento de las finalidades mencionadas en el párrafo anterior. Dicho interés legítimo se considera prevalente, teniendo en cuenta que el medio es idóneo para la finalidad perseguida, que el único dato que se graba es la voz y que los datos se conservan sólo durante el tiempo imprescindible. En concreto, las grabaciones se mantendrán almacenadas un máximo de 12 meses.</p>
        <h4>¿A qué destinatarios se comunicarán sus datos? </h4>
        <p>Los datos facilitados podrán ser cedidos a las siguientes entidades:</p>
        <ul>
        <li>A las empresas Nebrija para la remisión de comunicaciones comerciales sobre los servicios que ofrecen o eventos que desarrollen. En este sentido, las empresas que forman parte de Nebrija son las siguientes: Institutos Nebrija, Residencias Nebrija, Fundación Nebrija (www.fundacionnebrija.org), entidades que prestan servicios académicos, culturales o de hospedaje. Para poder realizar esta cesión de datos se requiere el consentimiento del interesado. Para esta finalidad, los datos se tratarán sobre la base de su consentimiento, no siendo obligatorio facilitarlos, en cuyo caso no podrá ser destinatario de la información indicada. Puede retirar el consentimiento en cualquier momento, si bien ello no afectará a la licitud de los tratamientos efectuados con anterioridad.</li>
            <li>A Residencias Nebrija o Institutos Nebrija: En el supuesto de que la petición o solicitud realizada por el usuario implique la necesidad de comunicar sus datos a estas entidades para que procedan a dar respuesta a las mismas o a gestionar la solicitud correspondiente.</li>
            <li>A las Administraciones Públicas competentes, incluidos jueces y tribunales, en los casos previstos en la Ley y para los fines en ella definidos.</li>
            <li>A las entidades financieras para el cobro de los servicios ofrecidos, a las entidades aseguradoras con las que la Universidad tenga contratados los seguros correspondientes y a las Administraciones Públicas en los casos previstos por la Ley y para las finalidades en ella definidas. De igual manera, en el supuesto de que el/la estudiante realice sus estudios académicos en alguno de los centros adscritos a la Universidad, sus datos serán cedidos a los mismos para el desarrollo de aquellos. Por otra parte, como consecuencia del servicio académico ofrecido por esta Universidad y para que el/la estudiante pueda completar sus estudios, sus datos podrán ser comunicados a las empresas de formación y empleo con las que este centro tiene suscritos acuerdos de colaboración, con la finalidad de facilitarle el acceso a puestos de empleo y formación práctica en empresas. En el supuesto de que el/la estudiante haya solicitado su inscripción en alguno de los clubes de la Universidad, sus datos serán cedidos a la Fundación Nebrija como entidad responsable de la gestión de los mismos. De igual manera, si el/la estudiante ha solicitado alojamiento, sus datos podrán ser comunicados a Residencias Nebrija, encargada de la gestión de los servicios de alojamiento a los/las estudiantes.</li>
            <li>Para los miembros de los clubes Nebrija, los datos podrán ser cedidos también a las entidades aseguradoras con las que la Fundación tenga contratados los seguros correspondientes, sobre todo como consecuencia de la realización de viajes o actividades de cualquier tipo organizadas por los clubes. Para estas últimas finalidades, sus datos también serán cedidos a las entidades que desarrollen tales viajes y actividades para que puedan gestionar adecuadamente su participación. De igual manera, sus datos podrán ser cedidos a la Universidad Nebrija cuando, como consecuencia de las ventajas ofrecidas por los clubes Nebrija a sus miembros, estos puedan disfrutar de las instalaciones o servicios académicos o de cualquier tipo ofrecidos por la Universidad, para lo cual se requiere que la Universidad conozca los datos de los miembros de los clubes Nebrija,, siendo esta cesión necesaria para el correcto desarrollo de los servicios ofrecidos por los clubs.</li>
            <li>A los padres o representantes legales de los/las estudiantes se les facilitará los datos relativos a las calificaciones, matrículas y becas de sus hijos o representados, siempre y cuando el/la estudiante haya manifestado su consentimiento previo o fuese dependiente económicamente de los mismos, en cuyo caso, cabe presumir con carácter general, la existencia de un interés legítimo prevalente en dicho acceso que habilitaría la cesión de los datos indicados sin necesidad de contar con el consentimiento previo del/la estudiante. En este caso, se informa al/la estudiante de que, con las limitaciones establecidas en la norma, puede ejercer su derecho de oposición al tratamiento.</li>
            <li>Los datos de identificación y de contacto de los/las estudiantes (nombre y apellido, teléfonos y direcciones de correo electrónico) podrán ser cedidos a empresas de rankings con la finalidad de confeccionar encuestas para evaluar la calidad y resultados de nuestra universidad y nuestros programas, tales como calidad de la docencia o grado de empleabilidad. Para poder realizar esta cesión de datos se requiere el consentimiento del interesado, siendo esta la base legitimadora. La autorización para esta cesión de datos es voluntaria y en caso de no otorgarse el/la estudiante no podría participar en las encuestas enviadas por las empresas de rankings y, por tanto, no se tendrían en cuenta sus valoraciones a la hora de elaborar los rankings correspondientes. Puede retirar el consentimiento en cualquier momento, si bien ello no afectará a la licitud de los tratamientos efectuados con anterioridad. Los datos personales podrán conservarse por la entidad cesionaria, para el fin indicado, durante todo el tiempo necesario para elaborar los rankings correspondientes. Posteriormente, sus datos serán eliminados.</li>
            <li>En el supuesto de que el/la usuario/a se descargue la aplicación de AppCrue, el acceso a las ventajas de Santander y/o Universia ofrecidas dentro del área de Ventajas, exige que el/la usuario/a consiente la cesión de sus datos a favor de estas entidades. Para más información sobre esta cesión de datos consulte el siguiente link: <a href="https://webappuniversitaria.universia.net/adenda/Politica_privacidad.html">https://webappuniversitaria.universia.net/adenda/Politica_privacidad.html</a><br /><br />Esta cesión a favor de ambas entidades deberá consentirse la primera vez que el/la usuario/a entre en una oferta de Santander o Universia. La legitimación para habilitar este tratamiento de datos encuentra su base jurídica en el consentimiento expreso del/la usuario/a. En caso de que el/la usuario/a no preste su consentimiento inicialmente o habiéndolo prestado, lo revoque en el futuro, no supondrá la pérdida de su condición de Usuario de la APP ni éste extremo afectará a la participación de éste en el resto de servicios ofertados por la APP.<br /><br />Adicionalmente, tal y como se informa en el enlace indicado, los datos del/la usuario/a podrán ser cedidos a las terceras entidades que ofrezcan ventajas a través de la sección de “Ventajas”. Esta cesión se hará siempre previa información y consentimiento del/la usuario/a, a través de las bases o condiciones legales que tendrá que aceptar para poder participar en tales ventajas, donde se detallarán los términos y condiciones de esta comunicación de datos.  
<br />
</li>
<li>Las entidades de mensajería a través de las que se realiza el servicio de entrega de productos adquiridos a través de la tienda on-line.</li>
        </ul>
            <h4>¿Cuáles son sus derechos cuando nos facilita sus datos?</h4>
            <p>En las condiciones previstas en el Reglamento General de Protección de Datos, los interesados podrán solicitar la limitación del tratamiento de sus datos o su portabilidad, en cuyo caso únicamente los conservaremos para el ejercicio o la defensa de reclamaciones.</p>
<p>En determinadas circunstancias y por motivos relacionados con su situación particular, los interesados podrán oponerse al tratamiento de sus datos. Si usted ha otorgado el consentimiento para alguna finalidad específica, tiene derecho a retirarlo en cualquier momento, sin que ello afecte a la licitud del tratamiento basado en el consentimiento previo a su retirada. En estos supuestos dejaremos de tratar los datos o, en su caso, dejaremos de hacerlo para esa finalidad en concreto, salvo por motivos legítimos imperiosos, o el ejercicio o la defensa de posibles reclamaciones.</p>
<p>Todos los derechos mencionados pueden ejercerse a través de los medios de contacto que figuran al principio de esta cláusula, utilizando los formularios accesibles a través del siguiente link <a href="https://www.nebrija.com/general/formularios.php">https://www.nebrija.com/general/formularios.php </a><br /><br />Frente a cualquier vulneración de sus derechos, especialmente cuando usted no haya obtenido satisfacción en su ejercicio, puede presentar una reclamación ante la Agencia Española de Protección de Datos (datos de contacto accesibles en www.aepd.es), u otra autoridad de control competente. También puede obtener más información sobre los derechos que le asisten dirigiéndose a dichos organismos.<br /><br />Con respecto al tratamiento de datos personales a través del Área de Ventajas de la AppCrue, los/las usuarios/as podrán ejercer frente a Santander y/o Universia sus derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento, portabilidad y a no ser objeto de decisiones individuales automatizadas, mediante el envío de un correo electrónico a <a href="mailto:privacidad@gruposantander.es">privacidad@gruposantander.es</a>en el caso de Santander o a appuniversitaria@universia.es en el caso de Universia, o por correo postal dirigiéndose a cualquiera de las sociedades a Juan Ignacio Luca de Tena 11 - 13, 28027 Madrid.</p>

<p>La información detallada sobre protección de datos de Santander para usuarios clientes se puede consultar en el Aviso Legal de la página web de Santander: <a href="https://www.bancosantander.es">www.bancosantander.es</a> y para potenciales en <a href="https://microsite.bancosantander.es/files/aviso_legal/informacion_ddc_pot.pdf ">https://microsite.bancosantander.es/files/aviso_legal/informacion_ddc_pot.pdf</a> 
</p>

    <h4>¿Qué responsabilidad tienes sobre tus datos personales?</h4>
        <p>Al facilitarnos sus datos personales, la persona que lo haga garantiza que es mayor de 14 años y que los datos facilitados son verdaderos, exactos, completos y actualizados.<br />El/la usuario/a es responsable de que la información que proporcione a través de esta Web sea cierta. A estos efectos, responde de la veracidad de todos los datos que comunique y mantendrá convenientemente actualizada la información facilitada, de tal forma que responda a su situación real. El/la usuario/a será responsable de las informaciones falsas o inexactas que proporcione y de los perjuicios que ello cause al titular de esta web o a terceros.</p>
        <h4>¿Qué medidas se toman en el tratamiento de datos personales?</h4>
        <p>Tenemos el firme compromiso de proteger los datos personales que tratamos. Utilizamos medidas, controles y procedimientos de carácter físico, organizativo y tecnológico, razonablemente fiables y efectivos, orientados a preservar la integridad y la seguridad de sus datos y garantizar su privacidad. <br /><br />Además, todo el personal con acceso a los datos personales ha sido formado y tiene conocimiento de sus obligaciones con relación a los tratamientos de sus datos personales.<br /><br />En el caso de los contratos que suscribimos con nuestros proveedores incluimos cláusulas en las que se les exige mantener el deber de secreto respecto a los datos de carácter personal a los que hayan tenido acceso en virtud del encargo realizado, así como implantar las medidas de seguridad técnicas y organizativas necesarias para garantizar la confidencialidad, integridad, disponibilidad y resiliencia permanentes de los sistemas y servicios de tratamiento de los datos personales.<br /><br />Todas estas medidas de seguridad son revisadas de forma periódica para garantizar su adecuación y efectividad.<br /><br />Sin embargo, la seguridad absoluta no se puede garantizar y no existe ningún sistema de seguridad que sea impenetrable por lo que, en el caso de cualquier información objeto de tratamiento y bajo nuestro control se viese comprometida como consecuencia de una brecha de seguridad, tomaremos las medidas adecuadas para investigar el incidente, notificarlo a la Autoridad de Control y, en su caso, a aquellos/as usuarios/as que se hubieran podido ver afectados para que tomen las medidas adecuadas. </p>
        <h4>¿Qué responsabilidad tienes en el tratamiento de datos de terceros?</h4>
        <p>En caso de que se hayan facilitado los datos personales de un tercero, es la exclusiva responsabilidad de quien lo haga haber obtenido previamente el consentimiento de esa persona para que sus datos sean tratados por nosotros, debiendo haberle informado previamente de todo lo previsto en el artículo 14 del Reglamento General de Protección de Datos.</p>
        


   

    </div>
  )
}

export default PoliticaDePrivacidadGrid